In [3]:
import pandas as pd
import os
df = pd.read_csv("train.csv")
df.head()

,id,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,...,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount
0,0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,...,2.0,17.0,372.0,5.0,2023-12-23 15:21:39.134960,Poor,No,Weekly,House,2869.0
1,1,39.0,Female,31678.0,Divorced,3.0,Master's,NaN,15.569731,Rural,...,1.0,12.0,694.0,2.0,2023-06-12 15:21:39.111551,Average,Yes,Monthly,House,1483.0
2,2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,...,1.0,14.0,NaN,3.0,2023-09-30 15:21:39.221386,Good,Yes,Weekly,House,567.0
3,3,21.0,Male,141855.0,Married,2.0,Bachelor's,NaN,10.938144,Rural,...,1.0,0.0,367.0,1.0,2024-06-12 15:21:39.226954,Poor,Yes,Daily,Apartment,765.0
4,4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,...,0.0,8.0,598.0,4.0,2021-12-01 15:21:39.252145,Poor,Yes,Weekly,House,2022.0

In [4]:
df.set_index("id",inplace=True)

In [5]:
df.head()

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount
id,,,,,,,,,,,,,,,,,,,,
0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,Premium,2.0,17.0,372.0,5.0,2023-12-23 15:21:39.134960,Poor,No,Weekly,House,2869.0
1,39.0,Female,31678.0,Divorced,3.0,Master's,NaN,15.569731,Rural,Comprehensive,1.0,12.0,694.0,2.0,2023-06-12 15:21:39.111551,Average,Yes,Monthly,House,1483.0
2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,Premium,1.0,14.0,NaN,3.0,2023-09-30 15:21:39.221386,Good,Yes,Weekly,House,567.0
3,21.0,Male,141855.0,Married,2.0,Bachelor's,NaN,10.938144,Rural,Basic,1.0,0.0,367.0,1.0,2024-06-12 15:21:39.226954,Poor,Yes,Daily,Apartment,765.0
4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,Premium,0.0,8.0,598.0,4.0,2021-12-01 15:21:39.252145,Poor,Yes,Weekly,House,2022.0

In [6]:
df.columns

Index(['Age', 'Gender', 'Annual Income', 'Marital Status',
       'Number of Dependents', 'Education Level', 'Occupation', 'Health Score',
       'Location', 'Policy Type', 'Previous Claims', 'Vehicle Age',
       'Credit Score', 'Insurance Duration', 'Policy Start Date',
       'Customer Feedback', 'Smoking Status', 'Exercise Frequency',
       'Property Type', 'Premium Amount'],
      dtype='object')

In [7]:
df["Customer Feedback"].unique()

array(['Poor', 'Average', 'Good', nan], dtype=object)

In [8]:
df.isnull().sum()

Age                      18705
Gender                       0
Annual Income            44949
Marital Status           18529
Number of Dependents    109672
Education Level              0
Occupation              358075
Health Score             74076
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [9]:
df["Age"].fillna(df["Age"].median(),inplace=True)

C:\Users\Dinesh\AppData\Local\Temp\ipykernel_18344\860536840.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(),inplace=True)

In [10]:
df["Annual Income"].fillna(df["Annual Income"].median(),inplace=True)

C:\Users\Dinesh\AppData\Local\Temp\ipykernel_18344\2973224462.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Annual Income"].fillna(df["Annual Income"].median(),inplace=True)

In [11]:
df.fillna({"Marital Status": df["Marital Status"].mode()[0]},inplace=True)

In [12]:
df.fillna({"Number of Dependents": df["Number of Dependents"].median()},inplace=True)

In [13]:
import numpy as np

In [14]:
df["Occupation"]=df["Occupation"].fillna(np.random.choice(df["Occupation"].dropna()))

In [15]:
df.fillna({"Health Score": df["Health Score"].median()},inplace=True)

In [16]:
df.fillna({"Previous Claims": df["Previous Claims"].median()},inplace=True)

In [17]:
df.fillna({"Vehicle Age": df["Vehicle Age"].median()},inplace=True)

In [18]:
df.fillna({"Credit Score": df["Credit Score"].median()},inplace=True)

In [19]:
 df.fillna({"Insurance Duration": df["Insurance Duration"].median()},inplace=True)

In [20]:
df["Customer Feedback"]= df["Customer Feedback"].fillna(np.random.choice(df["Customer Feedback"].dropna()))

In [21]:
#df.columns

In [22]:
 df["Policy Start Date"] = pd.to_datetime(df["Policy Start Date"],format="%Y-%m-%d %H:%M:%S.%f")

In [23]:
df["Year"] = df["Policy Start Date"].dt.year
df["Month"] = df["Policy Start Date"].dt.month
df["Day"] = df["Policy Start Date"].dt.day
df["Week"] = df["Policy Start Date"].dt.isocalendar().week
df["Num_of_week"]=df["Policy Start Date"].dt.day_of_week
df["Hour"] = df["Policy Start Date"].dt.hour
df["Minute"] = df["Policy Start Date"].dt.minute

In [24]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",10)

In [25]:
df.head()

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount,Year,Month,Day,Week,Num_of_week,Hour,Minute
id,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,Premium,2.0,17.0,372.0,5.0,2023-12-23 15:21:39.134960,Poor,No,Weekly,House,2869.0,2023,12,23,51,5,15,21
1,39.0,Female,31678.0,Divorced,3.0,Master's,Unemployed,15.569731,Rural,Comprehensive,1.0,12.0,694.0,2.0,2023-06-12 15:21:39.111551,Average,Yes,Monthly,House,1483.0,2023,6,12,24,0,15,21
2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,Premium,1.0,14.0,595.0,3.0,2023-09-30 15:21:39.221386,Good,Yes,Weekly,House,567.0,2023,9,30,39,5,15,21
3,21.0,Male,141855.0,Married,2.0,Bachelor's,Unemployed,10.938144,Rural,Basic,1.0,0.0,367.0,1.0,2024-06-12 15:21:39.226954,Poor,Yes,Daily,Apartment,765.0,2024,6,12,24,2,15,21
4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,Premium,0.0,8.0,598.0,4.0,2021-12-01 15:21:39.252145,Poor,Yes,Weekly,House,2022.0,2021,12,1,48,2,15,21

In [26]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

In [27]:
df.isnull().sum()

Age                     0
Gender                  0
Annual Income           0
Marital Status          0
Number of Dependents    0
                       ..
Day                     0
Week                    0
Num_of_week             0
Hour                    0
Minute                  0
Length: 27, dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df["Gender"] = enc.fit_transform(df["Gender"])
df["Marital Status"] = enc.fit_transform(df["Marital Status"])
df["Education Level"] = enc.fit_transform(df["Education Level"])
df["Occupation"] = enc.fit_transform(df["Occupation"])
df["Location"] = enc.fit_transform(df["Location"])
df["Policy Type"] = enc.fit_transform(df["Policy Type"])
df["Customer Feedback"] = enc.fit_transform(df["Customer Feedback"])
df["Smoking Status"] = enc.fit_transform(df["Smoking Status"])
df["Exercise Frequency"] = enc.fit_transform(df["Exercise Frequency"])
df["Property Type"] = enc.fit_transform(df["Property Type"])

In [30]:
df.head()

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount,Year,Month,Day,Week,Num_of_week,Hour,Minute
id,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,19.0,0,10049.0,1,1.0,0,1,22.598761,2,2,2.0,17.0,372.0,5.0,2023-12-23 15:21:39.134960,2,0,3,2,2869.0,2023,12,23,51,5,15,21
1,39.0,0,31678.0,0,3.0,2,2,15.569731,0,1,1.0,12.0,694.0,2.0,2023-06-12 15:21:39.111551,0,1,1,2,1483.0,2023,6,12,24,0,15,21
2,23.0,1,25602.0,0,3.0,1,1,47.177549,1,2,1.0,14.0,595.0,3.0,2023-09-30 15:21:39.221386,1,1,3,2,567.0,2023,9,30,39,5,15,21
3,21.0,1,141855.0,1,2.0,0,2,10.938144,0,0,1.0,0.0,367.0,1.0,2024-06-12 15:21:39.226954,2,1,0,0,765.0,2024,6,12,24,2,15,21
4,21.0,1,39651.0,2,1.0,0,1,20.376094,0,2,0.0,8.0,598.0,4.0,2021-12-01 15:21:39.252145,2,1,3,2,2022.0,2021,12,1,48,2,15,21

In [31]:
#df.to_csv("Dx.csv")

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200000 entries, 0 to 1199999
Data columns (total 27 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1200000 non-null  float64
 1   Gender                1200000 non-null  int64
 2   Annual Income         1200000 non-null  float64
 3   Marital Status        1200000 non-null  int64
 4   Number of Dependents  1200000 non-null  float64
 5   Education Level       1200000 non-null  int64
 6   Occupation            1200000 non-null  int64
 7   Health Score          1200000 non-null  float64
 8   Location              1200000 non-null  int64
 9   Policy Type           1200000 non-null  int64
 10  Previous Claims       1200000 non-null  float64
 11  Vehicle Age           1200000 non-null  float64
 12  Credit Score          1200000 non-null  float64
 13  Insurance Duration    1200000 non-null  float64
 14  Policy Start Date     1200000 non-null  datetime64[ns]
 15  Customer Feedback     1200000 non-null  int64
 16  Smoking Status        1200000 non-null  int64
 17  Exercise Frequency    1200000 non-null  int64
 18  Property Type         1200000 non-null  int64
 19  Premium Amount        1200000 non-null  float64
 20  Year                  1200000 non-null  int32
 21  Month                 1200000 non-null  int32
 22  Day                   1200000 non-null  int32
 23  Week                  1200000 non-null  UInt32
 24  Num_of_week           1200000 non-null  int32
 25  Hour                  1200000 non-null  int32
 26  Minute                1200000 non-null  int32
dtypes: UInt32(1), datetime64[ns](1), float64(9), int32(6), int64(10)
memory usage: 225.4 MB

In [33]:
#df

In [34]:
df.drop(["Policy Start Date"],axis=1,inplace=True)

In [35]:
pd.set_option("display.max_rows",None)

In [36]:
df.corr()

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount,Year,Month,Day,Week,Num_of_week,Hour,Minute
Age,1.000000,0.000215,0.000061,0.000225,0.001399,-0.000416,-0.000108,0.000813,0.001861,-0.000407,0.001544,-0.002436,0.002661,-0.000062,0.000565,-0.000628,0.000421,-0.001176,-0.002410,-0.003151,0.001196,-0.000596,0.000990,-0.001221,NaN,NaN
Gender,0.000215,1.000000,-0.000983,0.001285,0.000833,0.000558,0.001118,0.003412,0.001225,-0.001539,-0.000229,0.000949,0.000756,0.000266,0.000859,0.003187,-0.000568,-0.000994,0.000161,0.000446,0.001254,0.000557,0.001179,0.000016,NaN,NaN
Annual Income,0.000061,-0.000983,1.000000,0.004035,0.001920,0.000257,-0.001470,0.023301,0.000434,-0.000843,0.034777,-0.000438,-0.181180,0.000383,0.013421,-0.001492,0.001439,-0.000462,-0.009989,-0.009716,0.008825,0.000346,0.008318,0.000143,NaN,NaN
Marital Status,0.000225,0.001285,0.004035,1.000000,-0.000658,-0.000986,0.001402,0.001610,0.000519,0.000155,0.000242,0.001132,-0.002786,-0.000510,0.001181,-0.000266,-0.000247,-0.003362,0.003021,0.001594,-0.000903,0.002019,-0.000978,-0.000430,NaN,NaN
Number of Dependents,0.001399,0.000833,0.001920,-0.000658,1.000000,0.000340,0.000581,0.004831,-0.000347,-0.001181,-0.003277,0.001170,-0.001525,-0.000252,-0.000413,0.000598,-0.000471,0.002104,-0.000947,0.000358,-0.000443,0.000200,0.000162,-0.000928,NaN,NaN
Education Level,-0.000416,0.000558,0.000257,-0.000986,0.000340,1.000000,0.002014,0.001360,0.002941,0.001344,0.000245,0.000743,-0.002020,0.000575,0.000793,0.000424,0.001498,0.001245,-0.001121,0.000349,0.000176,-0.002491,-0.000010,0.001738,NaN,NaN
Occupation,-0.000108,0.001118,-0.001470,0.001402,0.000581,0.002014,1.000000,0.001289,0.000120,-0.001224,-0.002327,-0.000885,0.003257,0.001379,0.000796,-0.000675,-0.000670,-0.001230,-0.004555,0.002046,-0.000691,0.001759,-0.000362,-0.000318,NaN,NaN
Health Score,0.000813,0.003412,0.023301,0.001610,0.004831,0.001360,0.001289,1.000000,-0.002067,-0.002296,0.001779,0.000237,0.009947,0.002374,-0.000649,-0.002050,-0.000748,-0.001030,0.013976,-0.001667,0.000603,-0.000586,0.000729,0.000008,NaN,NaN
Location,0.001861,0.001225,0.000434,0.000519,-0.000347,0.002941,0.000120,-0.002067,1.000000,0.000331,-0.000860,-0.000009,-0.000547,0.001933,-0.001730,0.001860,0.000528,-0.000434,0.001059,-0.001317,-0.000140,0.001158,-0.000091,0.000683,NaN,NaN
Policy Type,-0.000407,-0.001539,-0.000843,0.000155,-0.001181,0.001344,-0.001224,-0.002296,0.000331,1.000000,-0.002091,0.001127,-0.001056,-0.000979,0.001003,-0.001745,0.002895,-0.001287,-0.000884,0.002634,0.000345,-0.000047,0.000366,-0.000630,NaN,NaN
Previous Claims,0.001544,-0.000229,0.034777,0.000242,-0.003277,0.000245,-0.002327,0.001779,-0.000860,-0.002091,1.000000,-0.000982,0.028795,0.002502,0.000972,-0.000852,-0.001078,-0.001652,0.039394,0.005300,-0.001818,0.000655,-0.001744,0.000605,NaN,NaN
Vehicle Age,-0.002436,0.000949,-0.000438,0.001132,0.001170,0.000743,-0.000885,0.000237,-0.000009,0.001127,-0.000982,1.000000,0.000470,0.003132,0.000249,0.000207,-0.000315,-0.002469,0.000391,0.001689,-0.000428,-0.000159,-0.000291,-0.000678,NaN,NaN
Credit Score,0.002661,0.000756,-0.181180,-0.002786,-0.001525,-0.002020,0.003257,0.009947,-0.000547,-0.001056,0.028795,0.000470,1.000000,0.000446,0.006709,0.001726,-0.001043,0.000786,-0.024471,-0.006872,0.003520,-0.000930,0.003547,-0.000547,NaN,NaN
Insurance Duration,-0.000062,0.000266,0.000383,-0.000510,-0.000252,0.000575,0.001379,0.002374,0.001933,-0.000979,0.002502,0.003132,0.000446,1.000000,-0.000290,0.000330,-0.000221,-0.000338,-0.000028,-0.001169,0.001950,-0.002147,0.001725,0.000841,NaN,NaN
Customer Feedback,0.000565,0.000859,0.013421,0.001181,-0.000413,0.000793,0.000796,-0.000649,-0.001730,0.001003,0.000972,0.000249,0.006709,-0.000290,1.000000,-0.000595,-0.000040,0.001966,0.009869,-0.000886,0.000319,-0.000191,0.000121,-0.000248,NaN,NaN
Smoking Status,-0.000628,0.003187,-0.001492,-0.000266,0.000598,0.000424,-0.000675,-0.002050,0.001860,-0.001745,-0.000852,0.000207,0.001726,0.000330,-0.000595,1.000000,0.001387,0.001469,0.000163,0.001644,-0.000024,-0.001363,-0.000150,0.001273,NaN,NaN
Exercise Frequency,0.000421,-0.000568,0.001439,-0.000247,-0.000471,0.001498,-0.000670,-0.000748,0.000528,0.002895,-0.001078,-0.000315,-0.001043,-0.000221,-0.000040,0.001387,1.000000,-0.000725,-0.001098,0.001674,-0.001892,-0.000562,-0.001152,0.000276,NaN,NaN
Property Type,-0.001176,-0.000994,-0.000462,-0.003362,0.002104,0.001245,-0.001230,-0.001030,-0.000434,-0.001287,-0.001652,-0.002469,0.000786,-0.000338,0.001966,0.001469,-0.000725,1.000000,-0.001222,0.001044,-0.002951,-0.000051,-0.002911,0.001426,NaN,NaN
Premium Amount,-0.002410,0.000161,-0.009989,0.003021,-0.000947,-0.001121,-0.004555,0.013976,0.001059,-0.000884,0.039394,0.000391,-0.024471,-0.000028,0.009869,0.000163,-0.001098,-0.001222,1.000000,-0.011084,0.006702,0.000291,0.006740,-0.000023,NaN,NaN
Year,-0.003151,0.000446,-0.009716,0.001594,0.000358,0.000349,0.002046,-0.001667,-0.001317,0.002634,0.005300,0.001689,-0.006872,-0.001169,-0.000886,0.001644,0.001674,0.001044,-0.011084,1.000000,-0.261312,-0.018947,-0.262044,-0.005348,NaN,NaN
Month,0.001196,0.001254,0.008825,-0.000903,-0.000443,0.000176,-0.000691,0.000603,-0.000140,0.000345,-0.001818,-0.000428,0.003520,0.001950,0.000319,-0.000024,-0.001892,-0.002951,0.006702,-0.261312,1.000000,0.007725,0.972219,0.002250,NaN,NaN
Day,-0.000596,0.000557,0.000346,0.002019,0.000200,-0.002491,0.001759,-0.000586,0.001158,-0.000047,0.000655,-0.000159,-0.000930,-0.002147,-0.000191,-0.001363,-0.000562,-0.000051,0.000291,-0.018947,0.007725,1.000000,0.067181,0.001996,NaN,NaN
Week,0.000990,0.001179,0.008318,-0.000978,0.000162,-0.000010,-0.000362,0.000729,-0.000091,0.000366,-0.001744,-0.000291,0.003547,0.001725,0.000121,-0.000150,-0.001152,-0.002911,0.006740,-0.262044,0.972219,0.067181,1.000000,0.001230,NaN,NaN
Num_of_week,-0.001221,0.000016,0.000143,-0.000430,-0.000928,0.001738,-0.000318,0.000008,0.000683,-0.000630,0.000605,-0.000678,-0.000547,0.000841,-0.000248,0.001273,0.000276,0.001426,-0.000023,-0.005348,0.002250,0.001996,0.001230,1.000000,NaN,NaN
Hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Minute,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df["Insurance Duration"].unique()

array([5., 2., 3., 1., 4., 6., 8., 9., 7.])

In [38]:
#df.columns

In [39]:
continues = ["Age","Annual Income","Health Score","Credit Score"]
categories =["Gender","Marital Status","Number of Dependents","Education Level","Occupation","Location","Policy Type","Previous Claims", 
             "Vehicle Age","Insurance Duration","Customer Feedback","Smoking Status","Exercise Frequency","Property Type"]

In [40]:
from scipy import stats

In [41]:
def two_sample(d1,d2):
    t=0
    f=0
    for i in range(31):
        sample1 = d1.sample(frac=0.03)
        sample2 = d2.sample(frac=0.03)
        t_test,p_value = stats.ttest_ind(sample1,sample2)
        if p_value < 0.05:
            f+=1
        else:
            t+=1
    if t>f:
        return True
    else:
        return False

In [42]:
def chisquare_test(d1,d2):
    return True if stats.chi2_contingency(pd.crosstab(d1,d2))[1]<0.05 else False

In [43]:
def annova_test(d1,d2):
  group=df[d2].unique()
  data={}
  for i in group:
    data[i]=df[d1][df[d2]==i]
  fvalue,p_value = stats.f_oneway(*[i for i in data.values()])
  return True if p_value<0.05 else False

In [44]:
final = {}
for i in df.columns:
    final[i] = {}
    for j in df.columns:
        if (i in continues) and (j in continues):
            result = two_sample(df[i],df[j])
        elif (i in categories) and (j in categories):
            result = chisquare_test(df[i],df[j])
        elif (i in continues) and (j in categories):
            result = annova_test(i,j)
        elif (i in categories) and (j in continues):
            result = annova_test(j,i)
        if result:
            final[i][j] = 1
        else:
            final[i][j] = 0

In [45]:
import pprint

In [46]:
final_df = pd.DataFrame(final)
final_df

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount,Year,Month,Day,Week,Num_of_week,Hour,Minute
Age,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1
Gender,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,1,1,1,1,1,1,1
Annual Income,0,0,1,1,1,1,1,0,0,0,1,0,0,0,1,0,1,0,1,1,1,1,1,1,1,1
Marital Status,0,1,1,1,0,0,1,1,0,0,0,0,1,1,1,0,0,1,1,1,1,1,1,1,1,1
Number of Dependents,0,0,1,0,1,0,0,1,0,0,1,1,0,1,0,0,1,1,1,1,1,1,1,1,1,1
Education Level,0,0,1,0,0,1,0,1,1,1,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1
Occupation,0,0,1,1,0,0,1,0,0,0,1,0,1,1,1,0,0,1,1,1,1,1,1,1,1,1
Health Score,0,1,0,1,1,1,0,1,1,1,1,0,0,1,0,1,0,1,1,1,1,1,1,1,1,1
Location,1,0,0,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1,1,1
Policy Type,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,1,0,1,1,1,1,1,1,1,1
Previous Claims,1,0,1,0,1,1,1,1,0,0,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,1
Vehicle Age,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1
Credit Score,0,0,0,1,0,1,1,0,0,0,1,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1
Insurance Duration,0,0,0,1,1,1,1,1,1,0,1,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1
Customer Feedback,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1
Smoking Status,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,1,1,1,1,1,1
Exercise Frequency,0,0,1,0,1,1,0,0,0,1,0,0,0,0,1,0,1,0,1,1,1,1,1,1,1,1
Property Type,0,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1
Premium Amount,0,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1
Year,0,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1
Month,0,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1
Day,0,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1
Week,0,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1
Num_of_week,0,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1
Hour,0,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1
Minute,0,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1

In [47]:
#import seaborn as sns
#sns.heatmap(final_df,annot=True,cmap="coolwarm")

In [48]:
#print(continues,type(continues))

In [49]:
for i in continues:
  print(i,"Skew :",df[i].skew(),"Kurtosis",df[i].kurtosis())

Age Skew : -0.012124039077023422 Kurtosis -1.1663719030495063
Annual Income Skew : 1.5229537478396937 Kurtosis 2.016891197172637
Health Score Skew : 0.3073021274990332 Kurtosis -0.6348953667048627
Credit Score Skew : -0.12578590724748864 Kurtosis -0.8414241913235956

In [50]:
for i in continues:
    if (df[i].skew() < 0.5 and df[i].skew() > -0.5) and (df[i].kurtosis() < 3 and df[i].kurtosis() > -3):
        continue
    print(i)

Annual Income

In [51]:
for i in continues:
    if (df[i].skew() < 0.5 and df[i].skew() > -0.5) and (df[i].kurtosis() < 3 and df[i].kurtosis() > -3):
        continue
    print(i)
    method = [1,-1,0,0.5,-0.5,2,-2]
    for j in method:
        print("Method",j,"Skew",pd.DataFrame(stats.boxcox(df[i],lmbda=j)).skew().values,"Kurtosis",pd.DataFrame(stats.boxcox(df[i],lmbda=j)).kurtosis().values)

Annual Income
Method 1 Skew [1.52295375] Kurtosis [2.0168912]
Method -1 Skew [-113.46016402] Kurtosis [30085.74576986]
Method 0 Skew [-1.04955485] Kurtosis [1.45537946]
Method 0.5 Skew [0.49718492] Kurtosis [-0.25847362]
Method -0.5 Skew [-9.85489349] Kurtosis [202.19241183]
Method 2 Skew [2.93478832] Kurtosis [8.94496845]
Method -2 Skew [-663.46841922] Kurtosis [546617.58773856]

In [52]:
df["Annual Income"] = stats.boxcox(df["Annual Income"],lmbda=0.5)

In [53]:
df.head()

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount,Year,Month,Day,Week,Num_of_week,Hour,Minute
id,,,,,,,,,,,,,,,,,,,,,,,,,,
0,19.0,0,198.489401,1,1.0,0,1,22.598761,2,2,2.0,17.0,372.0,5.0,2,0,3,2,2869.0,2023,12,23,51,5,15,21
1,39.0,0,353.966291,0,3.0,2,2,15.569731,0,1,1.0,12.0,694.0,2.0,0,1,1,2,1483.0,2023,6,12,24,0,15,21
2,23.0,1,318.012500,0,3.0,1,1,47.177549,1,2,1.0,14.0,595.0,3.0,1,1,3,2,567.0,2023,9,30,39,5,15,21
3,21.0,1,751.272859,1,2.0,0,2,10.938144,0,0,1.0,0.0,367.0,1.0,2,1,0,0,765.0,2024,6,12,24,2,15,21
4,21.0,1,396.251177,2,1.0,0,1,20.376094,0,2,0.0,8.0,598.0,4.0,2,1,3,2,2022.0,2021,12,1,48,2,15,21

In [54]:
x = df.iloc[:,:-8]
x.head()

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Customer Feedback,Smoking Status,Exercise Frequency,Property Type
id,,,,,,,,,,,,,,,,,,
0,19.0,0,198.489401,1,1.0,0,1,22.598761,2,2,2.0,17.0,372.0,5.0,2,0,3,2
1,39.0,0,353.966291,0,3.0,2,2,15.569731,0,1,1.0,12.0,694.0,2.0,0,1,1,2
2,23.0,1,318.012500,0,3.0,1,1,47.177549,1,2,1.0,14.0,595.0,3.0,1,1,3,2
3,21.0,1,751.272859,1,2.0,0,2,10.938144,0,0,1.0,0.0,367.0,1.0,2,1,0,0
4,21.0,1,396.251177,2,1.0,0,1,20.376094,0,2,0.0,8.0,598.0,4.0,2,1,3,2

In [55]:
y = df["Premium Amount"]
y.head()

id
0    2869.0
1    1483.0
2     567.0
3     765.0
4    2022.0
Name: Premium Amount, dtype: float64

In [56]:
#y.value_counts()

In [57]:
print(len(y.value_counts()))

4794

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((960000, 18), (240000, 18), (960000,), (240000,))

In [59]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor().fit(x_train,y_train)

In [ ]:
x_train.head()

In [ ]:
y_train.head()

In [63]:
import numpy as np
dx = np.array([[45,1,404.536,1,1,2,2,42,1,1,1,6,650,8,0,1,2,1]])

In [64]:
model.predict(dx)

d:\vscode\.venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([1168.])

In [66]:
test = pd.read_csv("test.csv")
test.head()

,id,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type
0,1200000,28.0,Female,2310.0,NaN,4.0,Bachelor's,Self-Employed,7.657981,Rural,Basic,NaN,19.0,NaN,1.0,2023-06-04 15:21:39.245086,Poor,Yes,Weekly,House
1,1200001,31.0,Female,126031.0,Married,2.0,Master's,Self-Employed,13.381379,Suburban,Premium,NaN,14.0,372.0,8.0,2024-04-22 15:21:39.224915,Good,Yes,Rarely,Apartment
2,1200002,47.0,Female,17092.0,Divorced,0.0,PhD,Unemployed,24.354527,Urban,Comprehensive,NaN,16.0,819.0,9.0,2023-04-05 15:21:39.134960,Average,Yes,Monthly,Condo
3,1200003,28.0,Female,30424.0,Divorced,3.0,PhD,Self-Employed,5.136225,Suburban,Comprehensive,1.0,3.0,770.0,5.0,2023-10-25 15:21:39.134960,Poor,Yes,Daily,House
4,1200004,24.0,Male,10863.0,Divorced,2.0,High School,Unemployed,11.844155,Suburban,Premium,NaN,14.0,755.0,7.0,2021-11-26 15:21:39.259788,Average,No,Weekly,House

In [85]:
test.drop("Policy Start Date",axis=1,inplace=True)

In [86]:
test.columns

Index(['id', 'Age', 'Gender', 'Annual Income', 'Marital Status',
       'Number of Dependents', 'Education Level', 'Occupation', 'Health Score',
       'Location', 'Policy Type', 'Previous Claims', 'Vehicle Age',
       'Credit Score', 'Insurance Duration', 'Customer Feedback',
       'Smoking Status', 'Exercise Frequency', 'Property Type'],
      dtype='object')

In [ ]:
test.isnull().sum()

In [81]:
test["Property Type"].unique()

array(['House', 'Apartment', 'Condo'], dtype=object)

In [83]:
test.fillna({"Age": test["Age"].median()},inplace=True)

test.fillna({"Annual Income": test["Annual Income"].median()},inplace=True)

test.fillna({"Marital Status": test["Marital Status"].mode()[0]},inplace=True)

test.fillna({"Number of Dependents": test["Number of Dependents"].median()},inplace=True)

test["Occupation"]=test["Occupation"].fillna(np.random.choice(test["Occupation"].dropna()))

test.fillna({"Health Score": test["Health Score"].median()},inplace=True)

test.fillna({"Previous Claims": test["Previous Claims"].median()},inplace=True)

test.fillna({"Vehicle Age": test["Vehicle Age"].median()},inplace=True)

test.fillna({"Credit Score": test["Credit Score"].median()},inplace=True)

test.fillna({"Insurance Duration": test["Insurance Duration"].median()},inplace=True)

test["Customer Feedback"]= test["Customer Feedback"].fillna(np.random.choice(test["Customer Feedback"].dropna()))

In [ ]:
test["Gender"] = enc.transform(test["Gender"])

In [ ]:
test["Marital Status"] = enc.transform(test["Marital Status"])

In [ ]:
test["Education Level"] = enc.transform(test["Education Level"])

In [ ]:
test["Occupation"] = enc.transform(test["Occupation"])

In [ ]:
test["Location"] = enc.transform(test["Location"])

In [ ]:
test["Policy Type"] = enc.transform(test["Policy Type"])

In [ ]:
test["Customer Feedback"] = enc.transform(test["Customer Feedback"])

In [ ]:
test["Smoking Status"] = enc.transform(test["Smoking Status"])

In [ ]:
test["Exercise Frequency"] = enc.transform(test["Exercise Frequency"])

In [ ]:
test["Property Type"] = enc.transform(test["Property Type"])